### ISSUE TITLE
Documentation rebranding

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#130]
There is extensive documentation which lives under the `docs/` directory in the repo that needs to be rebranded.

Action items:
* change all references to Dash to Energi
* chance all references to latest Dash version to the appropriate Energi version
* remove documentation pertaining to prior Dash versions
* update or verify all hyperlinks
* update or verify all images and icons

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Documentation rebranding](https://trello.com/c/cFGmvfFe/83-documentation-rebranding)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
