### ISSUE TITLE
Inconsistencies in masternode payments

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#134]
There are some inconsistencies in the payments that need to be investigated:
- The masternodes are already being paid, despite the fact that  the first masternode payment is to be made at 87600 blockHeight, as can be seen [here](https://explore.energi.network/tx/6925b7f26c1f227fd17fc948ed2ec68592b4ac43aba1fee3b95f2213f37881c1).
- Sporadically, this error also comes up which may or may not have to do with this: `CMasternodePayments::ProcessBlock -- ERROR: Failed to find masternode to pay`
- The payments being made are inconsistent to the actually configured amount.

**Comment by yghazi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Masternode payment inconsistencies](https://trello.com/c/J9sK9c9z/84-masternode-payment-inconsistencies)

**Comment by ediston** [comment]
Quick question on this issue. 
Can you please list steps to reproduce this error?

**Comment by yghazi** [comment]
As far as I recall, it was mainly just mining that would produce this. Could be when the masternode was down, but still, it shouldn't be paying the masternode already.

**Comment by RyanLucchese** [comment]
Fixed by #151
