### ISSUE TITLE
DoS protection: quick discard blocks with invalid mixhash

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#157]
The mixhash field of the block header serves to provide a way to quickly prove that blocks were cryptographically mined, thus making DoS attacks which submit invalid blocks to the network more difficult.

We need to add this validation into Energi. The mixhash and nonce must satisfy a mathematical condition specified in the Ethereum Yellowpaper section 4.3.4. Block Header Validity, (44) for a block to be considered valid. This should be the first check in the series of block validity checks.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [DoS protection: quick discard blocks with invalid mixhash](https://trello.com/c/EC6vn21u/101-dos-protection-quick-discard-blocks-with-invalid-mixhash)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
