### ISSUE TITLE
Clash in default and 60x testnet traffic 

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#171]
There seems to be some kind of interference where default testnet nodes are talking to testnet 60x nodes, which is causing some problems.

**Comment by RyanLucchese** [comment]
Fixed by #174

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clash in default and 60x testnet traffic](https://trello.com/c/5jWnflym/105-clash-in-default-and-60x-testnet-traffic)
