### ISSUE TITLE
Core dump in transactions tab

### ISSUE THREAD

**Issue by levongh** [energicryptocurrency/energi#196]
Steps to reproduce
1. Open wallet energi-qt
2. Go to Transactions tab
3. right click under transactions table view

**Comment by levongh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Core dump in transactions tab](https://trello.com/c/Yrnz0kp2/122-core-dump-in-transactions-tab)

**Comment by RyanLucchese** [comment]
Fixed by #198
