### ISSUE TITLE
On "Wallet Repair" tab data corrupted

### ISSUE THREAD

**Issue by levongh** [energicryptocurrency/energi#199]
![bug](https://user-images.githubusercontent.com/14893358/34813289-d7c95b7e-f6c2-11e7-82cb-984e507e6844.PNG)

**Comment by levongh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [On "Wallet Repair" tab data corrupted](https://trello.com/c/8whKvu6T/124-on-wallet-repair-tab-data-corrupted)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
