### ISSUE TITLE
Build: Travis CI is unable to build MacOS executables

### ISSUE THREAD

**Issue by ankisharmadel** [energicryptocurrency/energi#20]
Travis CI require MacOS SDK link for compilation. Dash is using "https://dash.org/depends-sources/sdks", however, SDK is not present at this link. Travis is reporting same problem for dash build.

Next step: MacOS SDK 10.9 needs to be uploaded on energi.world website or any other stable weburl

Logs:
[TravisMacOS build.txt](https://github.com/energicryptocurrency/energi/files/1220428/TravisMacOS.build.txt)

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Build: Travis CI is unable to build MacOS executables](https://trello.com/c/pdkJ8xlk/35-build-travis-ci-is-unable-to-build-macos-executables)

**Comment by ankisharmadel** [comment]
Issue closed by changing SDK path to "SDK_URL=https://bitcoincore.org/depends-sources/sdks" in travis configuration
