### ISSUE TITLE
Wallframe background image (drkblue_walletFrame_bg.png) is not loaded in traditional style

### ISSUE THREAD

**Issue by sedrakGR** [energicryptocurrency/energi#201]
In other styles this image is loading correctly but in "trad" style no.
![untitled](https://user-images.githubusercontent.com/4750797/34816353-2146de06-f6ce-11e7-87ce-5a0093acda1d.png)

**Comment by sedrakGR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Wallframe background image (drkblue_walletFrame_bg.png) is not loaded in traditional style](https://trello.com/c/QR2CyZXK/123-wallframe-background-image-drkbluewalletframebgpng-is-not-loaded-in-traditional-style)

**Comment by RyanLucchese** [comment]
Fixed by #202
