### ISSUE TITLE
getblocktemplate does not work properly

### ISSUE THREAD

**Issue by levongh** [energicryptocurrency/energi#204]
getblocktemplate returns error in any case
error code: -9
error message:
Energi Core is not connected!

**Comment by levongh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [getblocktemplate does not work properly](https://trello.com/c/SaTwNAOl/126-getblocktemplate-does-not-work-properly)

**Comment by RyanLucchese** [comment]
Not a defect - the problem is the test net lacks recent blocks. I have mined some new blocks on the longest testnet chain, @levongh can you confirm `getblocktemplate` is working as expected now?

**Comment by levongh** [comment]
Checked now it works as expected.
