### ISSUE TITLE
QA: txn_doublespend.py test case is failing

### ISSUE THREAD

**Issue by ankisharmadel** [energicryptocurrency/energi#21]
Steps to reproduce:
1 - Compile enrgi code on Linux
2 - Go in the base directory
3. - execute qa/rpc-tests/txn_doublespend.py --mineblock

Script goes in to hang state

![image](https://user-images.githubusercontent.com/28820514/29249258-8affcb9e-806f-11e7-99cd-6298661d1bf0.png)

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: txn_doublespend.py test case is failing](https://trello.com/c/zB6gPmtl/34-qa-txndoublespendpy-test-case-is-failing)
