### ISSUE TITLE
Scrollbar overlaps the amount column on the transactions page

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#212]
When there are many transactions, the scroll bar on the transactions page overlaps the transaction amount. When there are not enough transactions to have a scrollbar, everything displays correctly as in the two following screenshots:

<img width="1320" alt="screen shot 2018-01-21 at 15 13 13" src="https://user-images.githubusercontent.com/5231832/35199630-d30e8f34-febd-11e7-9676-c1ea6a8a3641.png">
<img width="1320" alt="screen shot 2018-01-21 at 15 13 19" src="https://user-images.githubusercontent.com/5231832/35199631-d4793950-febd-11e7-9511-754a82efbc37.png">

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scrollbar overlaps the amount column on the transactions page](https://trello.com/c/lQBoskxw/130-scrollbar-overlaps-the-amount-column-on-the-transactions-page)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
