### ISSUE TITLE
Masternodes aren't getting paid on 60x

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#214]
On the 60x testnet, masternodes started getting paid at the specified blockHeight but the amount is wrong.

**Comment by yghazi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Masternodes aren't getting paid on 60x](https://trello.com/c/CT4bhAwA/133-masternodes-arent-getting-paid-on-60x)

**Comment by RyanLucchese** [comment]
Fixed by #216
