### ISSUE TITLE
Option for disabling notifications for the wallet

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#215]
There should be an option to enable or disable notifications in the QT wallet.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Option for disabling notifications for the wallet](https://trello.com/c/H6MXnSMn/139-option-for-disabling-notifications-for-the-wallet)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
