### ISSUE TITLE
QA: multi_rpc.py test case is failing

### ISSUE THREAD

**Issue by ankisharmadel** [energicryptocurrency/energi#22]
Steps to reproduce:
1 - Compile enrgi code on Linux
2 - Go in the base directory
3. - execute qa/rpc-tests/multi_rpc.py 

Script goes in to hang state:
![image](https://user-images.githubusercontent.com/28820514/29249304-3a4c8448-8070-11e7-89f7-fc3207cba513.png)

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: multi_rpc.py test case is failing](https://trello.com/c/qMoasZG8/33-qa-multirpcpy-test-case-is-failing)
