### ISSUE TITLE
UI Freeze during DAG epoch switch

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#223]
energi.conf requirements:
`usedag=1`

When the epoch is switched and a new DAG is generated, the UI locks up due to lack of callback from the DAG generation function. Generating the new DAG should be done in a separate thread to prevent this.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [UI Freeze during DAG epoch switch](https://trello.com/c/pvVaoCew/144-ui-freeze-during-dag-epoch-switch)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
