### ISSUE TITLE
QA: Replacing dash.conf with energi.conf in util.py is causing script to go in to hang state

### ISSUE THREAD

**Issue by ankisharmadel** [energicryptocurrency/energi#23]
After successful compilation on linux, if test framework is run then it is going in to hang state.

The workaround is to replace energi.conf with dash.conf in util.py file.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [QA: Replacing dash.conf with energi.conf in util.py is causing script to go in to hang state](https://trello.com/c/fjbkStFG/32-qa-replacing-dashconf-with-energiconf-in-utilpy-is-causing-script-to-go-in-to-hang-state)

**Comment by ankisharmadel** [comment]
This issue was present because of using incorrect environment variable name.
