### ISSUE TITLE
Memory grows on switching DAG between epochs.

### ISSUE THREAD

**Issue by sedrakGR** [energicryptocurrency/energi#237]
When switching ActiveDag memory grows.
Maybe Dag unload is not working properly

**Comment by sedrakGR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Memory grows on switching DAG between epochs](https://trello.com/c/9SBfYdC0/146-memory-grows-on-switching-dag-between-epochs)

**Comment by andvgal** [comment]
The caching problem has been investigated and fixed for the next releases.
