### ISSUE TITLE
When best chain index is not equal to the sumbitted one's index, it should be ignored instead of calling abortNode in ConnectTip

### ISSUE THREAD

**Issue by sedrakGR** [energicryptocurrency/energi#277]
In ActivateBestChainStep
if (!ConnectTip(state, chainparams, pindexConnect, pindexConnect == pindexMostWork ? pblock : NULL)) { pindexConnect and pindexMostWork are not equal so it sends NULL, and ConnectTip calls abortNode.
This should be ignored instead of calling abortNode when this happens (due to low difficulty/regtest mining).

**Comment by sedrakGR** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [AbortNode called due to low difficulty chain processing](https://trello.com/c/WVZCwJKr/170-abortnode-called-due-to-low-difficulty-chain-processing)

**Comment by andvgal** [comment]
Closing internal issue on GitHub.
