### ISSUE TITLE
sort masternode outputs by block height vs alphabetical 

### ISSUE THREAD

**Issue by mikeytown2** [energicryptocurrency/energi#286]
Nice to have

**Comment by andvgal** [comment]
@mikeytown2 I am not sure the purpose of this request.

I guess more important is current rank of the MN. There is `masternode list rank` for that.

**Comment by mikeytown2** [comment]
If you create multiple collateral transactions it's hard to tell what's the latest one as `masternode outputs` prints out the transactions in alphabetical order. Sorting by block height so the latest ones are at the bottom would make it easy to figure out what the latest collateral tx should be used for masternode creation.

**Comment by andvgal** [comment]
Well, obvious won't fix with Gen 3 now.
