### ISSUE TITLE
energi team

### ISSUE THREAD

**Issue by baothybach** [energicryptocurrency/energi#290]
go to the mooon

**Comment by vijay1968** [comment]
Energi is the best cryptocurrency in presently we truest on energi

**Comment by Alex3590** [comment]
привет, супер, как верификацию пройти??вы админ энерджи?

ср, 31 окт. 2018 г. в 13:42, Vijaypal singh <notifications@github.com>:

**Comment by seitenwahl** [comment]
???

**Comment by hedy99** [comment]
Nice

**Comment by Alex3590** [comment]
hi

чт, 15 нояб. 2018 г. в 09:27, ryoma1402 <notifications@github.com>:

**Comment by seitenwahl** [comment]
its running?

**Comment by cryptodhamaka** [comment]
It's live

**Comment by kimtanrt17** [comment]
Nice

Vào Thứ Năm, 15 tháng 11, 2018, cryptodhamaka <notifications@github.com> đã
viết:

**Comment by MARCUS2928** [comment]
hello
