### ISSUE TITLE
Your PGP public key for code releases

### ISSUE THREAD

**Issue by pub-key-crypto** [energicryptocurrency/energi#294]
Please post your  PGP public key for the energicore and energiminer sig files.
We need it to verify your signature on the energicore and energiminer releases.

Here is the error:
Tuesday, January 01, 2019 18:30:28

gpg --verify energicore-1.3.0-win64-setup.exe.sig
gpg: Can't check signature: No public key

gpg --verify energiminer-2.2.1-Windows.zip.sig
gpg: Can't check signature: No public key

--Thanks in advance

**Comment by escape2000** [comment]
I'm sorry I don't know how to do that? I went to GitHub but it didn't explain how to post my pgp code??? Can you please tell me how to fix this? -chrissi

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pub-key-crypto** [comment]
Hi Chrissi,

For a devs or release engineer for Energi...

First of all, the signature files (.sig) are in good shape. Good start...

Where's the PGP public key?
1. The tools that is used to create the SIG files is using a private key that was generated ahead of time.
2. The same tool can be used to export the matching PUBLIC key for sharing. Caution: Make sure it the PUBLIC key!!
3. Place the PGP public key text inside a plain text file text file and post with your releases.

Example of PGP public key text:

-----BEGIN PGP PUBLIC KEY BLOCK-----

[Bunch of hexadecimal text]

-----END PGP PUBLIC KEY BLOCK-----

Here are some examples:
https://www.gnupg.org/gph/en/manual/x56.html
https://accc.uic.edu/answer/how-do-i-share-pgp-keys-others
https://gpgtools.tenderapp.com/kb/gpg-keychain-faq/how-to-find-and-share-your-public-key

--cheers!

**Comment by andvgal** [comment]
All keys are published https://www.energi.world/downloads/

As this is a fake social activity, it is reported.
