### ISSUE TITLE
energid-energid.o: file is empty

### ISSUE THREAD

**Issue by kek-mex** [energicryptocurrency/energi#298]
Im having problems with compiling energi from the source code. Can anyone help me with this issue?

This is what i try to compile with.
1. ./autogen.sh
2. ./configure --with-incompatible-bdb
3. make -j3

Specs:
- OS: Manjaro Openbox 18.0.4
- CPU: AMD Ryzen 3 2200G
- RAM: 4GB + (GB SWAP
- Disk size: 240GB
- Disk Type (HD/SDD): SSD

Here is paste from my terminal: [https://pastebin.com/Lhb0x5KU](https://pastebin.com/Lhb0x5KU)

**Comment by andvgal** [comment]
@kek-mex please follow https://github.com/energicryptocurrency/energi/blob/master/energi-docs/devenv.md

Other build methods are not official supported.

**Comment by kek-mex** [comment]
Hey. Thanks for your reply @andvgal.  However i ran into another problem, as i never have used cid before. It says that i need to set HOST env: https://pastebin.com/xhr3XDYz

**Comment by andvgal** [comment]
I assume the case is resolved? Please re-open if not.

**Comment by kek-mex** [comment]
> I assume the case is resolved? Please re-open if not.

Yes. Just had to edit the futoin.json a little bit on manjaro.

I had to change from this:

`"if [ -z \"$HOST\" ]; then echo 'Please set HOST env (e.g. x86_64-linux-gnu)'; exit 1; fi"`

To this:

`"if [ -z \"$HOST\" ]; then echo 'Please set HOST env (e.g. x86_64-linux-gnu)'; exit 1; fi"`
