### ISSUE TITLE
GUI Client in testnet is crashing on block # 462938

### ISSUE THREAD

**Issue by jjmr007** [energicryptocurrency/energi#303]
### Description

During sync, at block 462938 an error message frame appears: MinGW Runtime Assertion; 

Asertion failed!

Program C:\Program Files\EnergiCore\energi-qt.exe
File: /home/jenkins/workspace/Core_Release_windows/src/net_processing.cpp, Line 922
Expresion: state.GetRejectCode() < REJECT_INTERNAL

### Can you reliably reproduce the issue?

yes

#### If so, please list the steps to reproduce below:

1. Go to folder C:\Users\ (MyUser) \AppData\Roaming\EnergiCore and delete the testnet1 folder
2. run cmd.exe for this folder and run: >energi-qt -testnet
3. wait to start sync, at the block 462938 it crashes

### Expected behaviour

The clien should syncronize without issues (as it does in mainnet)

### Actual behaviour

node crashes while trying to sync at block 462938

### Screenshots.

![Bug Block 2](https://user-images.githubusercontent.com/17028457/68506513-2a5b2400-0240-11ea-8eab-39dde2a9c30e.PNG)

![Bug Block 3](https://user-images.githubusercontent.com/17028457/68506561-452d9880-0240-11ea-927d-39d6018431c9.PNG)

### What version of Dash Core are you using?

Energi Core version 2.2.1 as downloaded from:
https://s3-us-west-2.amazonaws.com/download.energi.software/releases/energi/v2.2.1/energicore-2.2.1-win64-setup.exe

### Machine specs:

- OS: windows 7; 64 bits
- CPU: intel core i5-4460
- RAM: 16 GB
- Disk size: 2 TB
- Disk Type (HD/SDD): ATA

### Any extra information that might be useful in the debugging process.

[debug.log](https://github.com/energicryptocurrency/energi/files/3826062/debug.log)

**Comment by andvgal** [comment]
Testnet is running a hard fork version.

Please consider using v2.3.0.3 pre-release: https://github.com/energicryptocurrency/energi/releases/tag/v2.3.0.3

It was dated Sep 5, but official release got canceled.

Below are some of valid peer lists:

- 54.184.183.8:19797
- 34.220.237.176:19797
- 94.130.208.211:19797

**Comment by jjmr007** [comment]
To soon for close this issue... 

I installed the new version v2.3.0.3, added the recommended nodes, but it's still crashing

**Comment by andvgal** [comment]
As you can see, it is not crashing. It is exiting on assertion because your local blockchain data has blocks which violate the hardfork one.

You can try `-reindex`.

Otherwise, Gen 2 is End-of-Life as Gen 3 is anticipated in near future.

**Comment by jjmr007** [comment]
Once installed the new version, I erased the testnet1 folder, and started from scratch.
The sync stopped at the same block. Does it makes any difference to use `-reindex`?

**Comment by jjmr007** [comment]
Trying with `-reindex` the node got stuck on block #462927

![Reindex](https://user-images.githubusercontent.com/17028457/68522864-15ee4a00-0287-11ea-8b1e-1f3a7064a96e.PNG)

the node start reindexing

![Reindex_2](https://user-images.githubusercontent.com/17028457/68522872-3ae2bd00-0287-11ea-95bb-a9fd0b302511.PNG)

then reindexing stops on block # 462927

![Reindex 4 stucked at block 462927](https://user-images.githubusercontent.com/17028457/68522998-ec362280-0288-11ea-86e3-5065884195e5.PNG)

Based on what you say this issue is has no priority due to the next migration to Gen3, but clearly it is a bug.
and, it is ok to leave closed an unfixed issue?
furthermore, do you mean that windows users won't have testnet until Gen3 is on?

**Comment by andvgal** [comment]
There can be rogue peers on the network which prevent sync to complete. You can enable debug messages `debug 1` in console and then check debug.log for more information. If you find something, please let us know.

Gen 2 testnet nodes we use are in sync, that can be proved by testnet explorer: https://explorer.test.energi.network/

Otherwise, you may want to use Gen 3 testnet, if you are going to work on a new project: https://medium.com/energi/energi-3-0-public-testing-now-open-609171a81312
