### ISSUE TITLE
How to get Energi Wallet running on Raspberry Pi?

### ISSUE THREAD

**Issue by FCU4ever** [energicryptocurrency/energi#304]
Hello,

I'm new to the Raspberry Pi and trying to get the NRG Core Cryptocurrency wallet running on my Raspberry. Finally I was able to compile the files after this commands:

Download and install the newest updates
sudo apt-get update && sudo apt-get upgrade

Install the following major dependencies packages
sudo apt-get install git build-essential libtool autotools-dev autoconf pkg-config libssl-dev libcrypto++-dev libevent-dev libminiupnpc-dev libgmp-dev libboost-all-dev devscripts libdb++-dev libsodium-dev

Install the following QT dependencies packages
sudo apt-get install libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libcrypto++-dev libminiupnpc-dev qt5-default

Install bitcoin PPA files
cd /etc/apt/sources.list.d/

sudo nano bitcoin.list

Add this line to the file:
deb-src http://ppa.launchpad.net/bitcoin/bitcoin/ubuntu artful main

Close file

sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv C70EF1F0305A1ADB9986DBD8D46F45428842CE5E

sudo apt-get update

Clone Github
cd
git clone https://github.com/energicryptocurrency/energi.git

Install
Libdb4.8
Libdb4.8-dev
Libdb++
Libdb4.8++-dev

Compile the wallet
cd energi
./autogen.sh
./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf
make
sudo make install

After compiling I see the files in /usr/local/bin
![0DD205CB-BD18-49E4-99D4-BE26437F7223](https://user-images.githubusercontent.com/37446406/75634332-36169000-5c0d-11ea-97cc-706b6390db7c.jpeg)

No I need to know how to use this files? Can someone help me please?

**Comment by andvgal** [comment]
Please contact our Support for general questions: https://www.energi.world/contact-us/

BTW, our Gen 2 software passes away and we are going to provide many more supported platform for Gen 3.
