### ISSUE TITLE
energicore-2.4.0, lack of GLIBC_2.27 libraries

### ISSUE THREAD

**Issue by Shekelme** [energicryptocurrency/energi#305]
I see these error messages when I'm trying to open newest Energi QT wallet energicore-2.4.0:

`./energi-qt: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by ./energi-qt)
./energi-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.23' not found (required by ./energi-qt)
./energi-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.11' not found (required by ./energi-qt)
./energi-qt: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by ./energi-qt)`

I'm under Linux Mint 18.3 with the packages updated just now.

**Comment by andvgal** [comment]
Unfortunately, the latest packages are built for Ubuntu 18.04 LTS or later. That corresponds to Mint 19.x or later.

If system upgrade is not acceptable for you, and/or you are not familiar with building software on your own, then you can do migration using [Gen 3 Nexus](https://gen3.energi.network/coin-migration) (suggested) or Gen 3 Core Node console.

Please contact our Support Team for further assistance: https://docs.energi.software/en/support/help-me
