### ISSUE TITLE
Pre-compute next DAG, cache & seedhash

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#58]
In order to facilitate smooth mining and verifying, the next DAG should be pre-computed. At the time blocks are added to the chain, if the chainheight exceeds the current epoch we should swap with the next DAG by calling ActiveDAG().

This depends on egihash issues 33 and 34:
https://github.com/energicryptocurrency/egihash/issues/33
https://github.com/energicryptocurrency/egihash/issues/34

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Pre-compute next DAG, cache & seedhash](https://trello.com/c/bs3qYf0R/31-pre-compute-next-dag-cache-seedhash)

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
