### ISSUE TITLE
Changing coin emission and distribution

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#79]

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Changing coin emission and distribution](https://trello.com/c/wiBcUjg7/6-changing-coin-emission-and-distribution)

**Comment by amermufti** [comment]
Will be changing main.cpp:GetMasternodePayment() function to set the master node share to 0.6 of blockValue.  blockValue already has 50% deducted at coinbase creation (10% founder, 40% budget). 

0.6 of the remaining 50% is 30%, which is the share specified for master nodes in energi.world. The 20% remainder is given to the miner per the logic in: masternode-payments.cpp:CMasternodePayments().

This implements the 10/20/30/40 allocation in energi.world

**Comment by amermufti** [comment]
Done

**Comment by RyanLucchese** [comment]
Coin emission rate accuracy improved by #102
