### ISSUE TITLE
Change network message magic bytes

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#83]
There are magic bytes which identify the start of messages of the bitcoin/dash protocols. These should be changed so Energi messages are easily identified, and bad traffic quickly discarded.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change network message magic bytes](https://trello.com/c/6dUF4dpB/47-change-network-message-magic-bytes)

**Comment by amermufti** [comment]
Magic bytes changed for all three nets in src/chainparams.cpp
