### ISSUE TITLE
Add DAG progress callbacks to the wallet splashscreen

### ISSUE THREAD

**Issue by yghazi** [energicryptocurrency/energi#88]
Right now, the wallet splash screen doesn't show the DAG progress, so that needs to be added.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add DAG progress callbacks to the wallet splashscreen](https://trello.com/c/jDeTcoTf/53-add-dag-progress-callbacks-to-the-wallet-splashscreen)

**Comment by RyanLucchese** [comment]
Fixed by #112
