### ISSUE TITLE
Review EGI units

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#90]
Currently the EGI units listed in the energi-qt wallet are:
 * tEGI
 * mtEGI
 * utEGI
 * tduffs

Some of these don't seem right. @TommyWorldPower can you comment regarding these units?

<img width="1051" alt="screen shot 2017-09-29 at 22 06 58" src="https://user-images.githubusercontent.com/5231832/31042334-bb59d376-a562-11e7-9326-b4568694a14a.png">

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Review EGI units](https://trello.com/c/1b4B0iMq/50-review-egi-units)

**Comment by TommyWorldPower** [comment]
I’m not sure about the units, do we need anything other than just EGI?

**Comment by yghazi** [comment]
Actually, Vivek changed the units for testnet to include the prefix t, so EGI becomes tEGI and so forth. As for the rest, they're just subunits. The duffs are the only thing I've got a problem with since they're named after Dash's founder, Evan Duffield.

**Comment by TommyWorldPower** [comment]
Got it, so then we should change duffs (the last subunit) to whatever the scientific subunit for that is, yeah?

**Comment by TommyWorldPower** [comment]
So it goes- milli (m),micro (u), nano (n)

**Comment by yghazi** [comment]
Exactly, something like that. Unless, you want something eccentric like wEGI or something.

**Comment by TommyWorldPower** [comment]
Ah but the problem is bitcoin and dash only go out 8 decimal places huh? (Nano is 9)... so then... for the time being we can do notation “z” for zeta. 

How’s that sound?

**Comment by TommyWorldPower** [comment]
So “zEGI” which would represent the smallest unit of EGI. Ofcourse the smallest unit may change in the future if we do a new blockchain in the future going out more than 8 decimal places... I still think it fits pretty well though.

**Comment by yghazi** [comment]
You say zeta, I think Jones. :wink: 

https://en.wikipedia.org/wiki/Zetta-

If we're going to 10^-12th decimal place, that would be pico, scientifically speaking.

**Comment by TommyWorldPower** [comment]
Haha fair enough, zetta is not the right one then. Can we easily change the # of decimal places? If so we can just stick with the standard scientific numbering - nano for 9 decimals our, and yeah pico for 12

**Comment by yghazi** [comment]
Sure, it's a pretty trivial change. Made the changes the first time around, so I can make them again.

**Comment by TommyWorldPower** [comment]
Great, that would be our solution then

**Comment by yghazi** [comment]
Rename `tduffs` to `atoms`

**Comment by RyanLucchese** [comment]
Fixed by #197
