### ISSUE TITLE
Create 60x testnet

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#91]
We need another testnet (testnet60x) to quickly test emission, masternode and voting changes. This testnet should run with 2 voting periods per day, putting it at 60x the pace of the standard test net and main net. The block timing doesn't have to change, but voting/masternode features should be quickly testable.

The maturity parameters should also be set to very low, possibly 0, values so that there is no requirement to wait for the chain to mature on the 60x testnet.

A command line argument -testnet60x will be required analogous to -testnet to enable it.

A new data dir ~/.energicore/testnet60x/ will be required to keep blockchain data separate from the regular testnet.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create 60x testnet](https://trello.com/c/w8Au99H9/51-create-60x-testnet)

**Comment by yghazi** [comment]
[f988223](https://github.com/energicryptocurrency/energi/commit/f988223d61387279f36c2ac9be6232a0deeb11cd)
