### ISSUE TITLE
Maturity parameters adjustment

### ISSUE THREAD

**Issue by RyanLucchese** [energicryptocurrency/energi#94]
In chainparams.cpp there are some maturity parameters which need adjusting for the main net and testnet. The 60x testnet should be designed with maturity parameters close to 0.

What we would like to achieve with the maturity parameters:
* initial voting cycle takes place 30 days after the genesis block
* masternode payments are delayed until 60 days after the genesis block
* transactions can begin within 100 blocks of launching the network

Please comment if other maturity parameters are discovered that should be taken into consideration.

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maturity parameters adjustment](https://trello.com/c/U5ci9g8H/55-maturity-parameters-adjustment)

**Comment by RyanLucchese** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Maturity parameters adjustment](https://trello.com/c/U5ci9g8H/55-maturity-parameters-adjustment)

**Comment by ediston** [comment]
Is this issue still relevant ?

**Comment by andvgal** [comment]
Closing internal issues on GitHub.
